### ISSUE TITLE
minor bug in the Generator view model

### ISSUE THREAD

**Issue by jyotishbora** [wilsonvargas/QRManager#2]
thank you for putting together the sample. found a small bug which is probably a oversight. 

in the QRGeneratorViewModel.cs  line 29,  EntryContent shouldnt be an empty string. 

 private void GenerateQRCode()
        {
            if (EntryContent == string.Empty)
            {
                TeamCode = EntryContent;
            }
        }
    }

**Comment by wilsonvargas** [comment]
Thanks! It was added 😃
